/**
 * Artifact drift checker — stale upstream detection.
 *
 * `ArtifactManager` records a sha256 baseline for every artifact it writes;
 * `advanceWorkflow` persists those baselines (hash + written_at) into
 * `state.artifact_hashes` and stamps `state.phase_runs[command]` with when the
 * phase last completed. This module compares baselines across the explicit
 * consumption edges in `edges.ts` and flags:
 *
 *   - `stale`    — the upstream was re-generated by the pipeline after the
 *                  downstream phase last ran. Attributed to the DOWNSTREAM
 *                  phase (re-running it clears the finding — "last ran" comes
 *                  from `phase_runs`, so even a byte-identical re-run clears).
 *   - `modified` — the upstream's on-disk content no longer matches its
 *                  recorded baseline (edited outside the pipeline). Attributed
 *                  to the PRODUCING phase (one finding per artifact): re-run
 *                  the producer to regenerate it, or bless the edit with
 *                  `oswald doctor --accept-drift`.
 *   - `unknown`  — no baseline to compare (state predates drift tracking, or
 *                  the file was archived/removed). NEVER treated as drift, so
 *                  pre-existing runs are never hard-failed.
 *   - `fresh`    — baseline matches and the downstream ran after the upstream.
 *
 * Deterministic and read-only: hashes file content, touches no state.
 */
import type { OswaldState } from "../state/index.js";
import { sha256Hex, type ArtifactManager } from "../artifacts/index.js";
import { CONSUMPTION_EDGES, producerOf, type ConsumptionEdge } from "./edges.js";

export type DriftStatus = "fresh" | "stale" | "modified" | "unknown";

export interface DriftFinding {
  /**
   * Phase (CLI verb) the finding is attributed to: the downstream consumer
   * for `stale`/`unknown`/`fresh`, the PRODUCING phase for `modified` (the
   * mismatch is between the upstream's disk content and its baseline, so only
   * re-generating or re-baselining the upstream can clear it).
   */
  phase: string;
  /** Upstream artifact filename. */
  upstream: string;
  status: DriftStatus;
  /** Human-readable explanation for reports and refusal messages. */
  detail: string;
}

export interface DriftReport {
  /** Every evaluated (phase, upstream) pair. */
  findings: DriftFinding[];
  /** Real drift: `stale` or `modified` findings. */
  drifted: DriftFinding[];
  /** `unknown (no baseline)` findings — reported, never blocking. */
  unknown: DriftFinding[];
  /** True when nothing drifted (unknown findings never fail the check). */
  ok: boolean;
}

export interface CheckDriftOptions {
  state: OswaldState;
  artifacts: ArtifactManager;
  /** Override the consumption-edge table (tests). */
  edges?: readonly ConsumptionEdge[];
}

/**
 * When the phase last ran. Prefers `state.phase_runs` (stamped on every
 * `advanceWorkflow`, INDEPENDENT of artifact content — so a re-run whose
 * outputs are byte-identical still counts and clears staleness). Falls back
 * to the latest `written_at` among the phase's output baselines for state
 * files recorded before phase-run tracking existed.
 */
function lastRanAt(edge: ConsumptionEdge, state: OswaldState): string | null {
  const runs = state.phase_runs ?? {};
  let latest: string | null = null;
  // ISO-8601 UTC strings from Clock.nowIso() compare lexicographically.
  for (const key of edge.command ? [edge.phase, edge.command] : [edge.phase]) {
    const ran = runs[key];
    if (ran !== undefined && (latest === null || ran > latest)) latest = ran;
  }
  if (latest !== null) return latest;

  const hashes = state.artifact_hashes ?? {};
  for (const out of edge.produces) {
    const rec = hashes[out];
    if (rec && (latest === null || rec.written_at > latest)) {
      latest = rec.written_at;
    }
  }
  return latest;
}

/** Whether any of the phase's output artifacts exist on disk. */
async function anyOutputOnDisk(
  edge: ConsumptionEdge,
  artifacts: ArtifactManager,
): Promise<boolean> {
  for (const out of edge.produces) {
    if (await artifacts.exists(out)) return true;
  }
  return false;
}

/** Run the drift check across the consumption-edge table. */
export async function checkDrift(options: CheckDriftOptions): Promise<DriftReport> {
  const { state, artifacts } = options;
  const edges = options.edges ?? CONSUMPTION_EDGES;
  const hashes = state.artifact_hashes ?? {};
  const findings: DriftFinding[] = [];
  // `modified` is per-ARTIFACT (attributed to its producer), not per-consumer:
  // report each hand-edited upstream exactly once.
  const modifiedReported = new Set<string>();

  for (const edge of edges) {
    const ranAt = lastRanAt(edge, state);
    // A phase that never produced anything has consumed nothing — skip.
    if (ranAt === null && !(await anyOutputOnDisk(edge, artifacts))) continue;

    for (const upstream of edge.consumes) {
      const baseline = hashes[upstream];
      const onDisk = await artifacts.exists(upstream);

      if (!baseline) {
        // No baseline to compare. Report (doctor) but never hard-fail (ship).
        if (onDisk) {
          findings.push({
            phase: edge.phase,
            upstream,
            status: "unknown",
            detail: "unknown (no baseline) — written before drift tracking",
          });
        }
        continue;
      }

      if (ranAt === null) {
        // Outputs exist on disk but were never recorded (pre-tracking run).
        findings.push({
          phase: edge.phase,
          upstream,
          status: "unknown",
          detail: `unknown (no baseline) — '${edge.phase}' outputs predate drift tracking`,
        });
        continue;
      }

      if (!onDisk) {
        // Archived/removed upstream: nothing to compare against; not drift.
        findings.push({
          phase: edge.phase,
          upstream,
          status: "unknown",
          detail: "unknown (no baseline) — upstream not on disk (archived or removed)",
        });
        continue;
      }

      const current = sha256Hex(await artifacts.read(upstream));
      if (current !== baseline.sha256) {
        if (!modifiedReported.has(upstream)) {
          modifiedReported.add(upstream);
          const producer = producerOf(upstream);
          findings.push({
            phase: producer ?? edge.phase,
            upstream,
            status: "modified",
            detail:
              `changed on disk outside the pipeline (baseline from ${baseline.written_at}); ` +
              (producer
                ? `re-run 'oswald ${producer}' to regenerate it, or keep the edit with 'oswald doctor --accept-drift'`
                : "re-baseline the edit with 'oswald doctor --accept-drift'"),
          });
        }
      } else if (baseline.written_at > ranAt) {
        findings.push({
          phase: edge.phase,
          upstream,
          status: "stale",
          detail: `re-generated at ${baseline.written_at}, after '${edge.phase}' last ran (${ranAt}); re-run 'oswald ${edge.phase}'`,
        });
      } else {
        findings.push({
          phase: edge.phase,
          upstream,
          status: "fresh",
          detail: "baseline matches; downstream is up to date",
        });
      }
    }
  }

  const drifted = findings.filter(
    (f) => f.status === "stale" || f.status === "modified",
  );
  const unknown = findings.filter((f) => f.status === "unknown");
  return { findings, drifted, unknown, ok: drifted.length === 0 };
}
